<?xml version="1.0" encoding="UTF-8"?>
<!--
    Arquivo principal de configuração do Maven (Project Object Model).
    Define informações do projeto, versão do Java e dependências.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- Versão padrão do modelo Maven -->
    <modelVersion>4.0.0</modelVersion>

    <!-- Coordenadas do Projeto (GAV) -->
    <groupId>com.cursojava</groupId>
    <artifactId>programa02</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- Configurações do Compilador Java -->
    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
    </properties>

    <!-- Dependências (Bibliotecas Externas) -->
    <dependencies>
        <!--
            MySQL Connector/J: Driver JDBC para comunicação entre Java e MySQL
            Fluxo: Java -> JDBC API -> MySQL Connector/J -> MySQL Server
        -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.7.0</version>
        </dependency>
    </dependencies>

</project>